version: '3'
networks:
  dimensi:
    external: true
services:
  nginx:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - /var/lib/nginx/data:/data
      - /var/lib/nginx/letsencrypt:/etc/letsencrypt
    networks:
      - dimensi

  wordpress:
    build:
      context: ../../services/wordpress/
      dockerfile: docker/Dockerfile
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: esteban
      WORDPRESS_DB_PASSWORD: estebitan
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ../../services/wordpress/html/:/var/www/html/
    networks:
      dimensi:
        aliases:
          - wordpress

  mysql:
    image: mysql:8.0.31
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_USER: esteban
      MYSQL_DATABASE: wordpress
      MYSQL_PASSWORD: estebitan
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - /var/lib/mysql-data:/var/lib/mysql
    networks:
      - dimensi

volumes:
  wordpress:
